
# DB config ??

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: 1234
  profiles:
    include: API-KEY
>>>>>>> master



  #JPA config
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true


chatgpt:
  api-key: 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
server:
  port: 8001
  api-key: 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
  max-tokens: 3000






